### ISSUE TITLE
Add instructions on how to install Pharo in WSL

### ISSUE THREAD

**Issue by fuhrmanator** [pharo-open-documentation/pharo-wiki#143]
Getting Pharo to run under WSL (Windows 10 Subsystem for Linux) was not obvious. Here's what I did:

- Install WSL https://docs.microsoft.com/en-us/windows/wsl/install-win10
- Install X Server for Windows (see https://jaipblog.wordpress.com/2018/01/21/running-linux-gui-apps-on-windows-10/, I used [VcXsrv](https://sourceforge.net/projects/vcxsrv/).
- Install [Mesa](https://wiki.debian.org/Mesa) with `sudo apt install mesa-utils` (needed because there are missing libraries for the x11 display used by Pharo).
- Install Pharo:
```ShellSession
$ mkdir MyPharo
$ cd MyPharo/
$ curl -L https://get.pharo.org/64/ | bash
```
The last step can also be the Pharo Launcher.

**Comment by fuhrmanator** [comment]
Also, the Mesa dependency may be overkill. On the Pharo install page at https://pharo.org/web/gnu-linux-installation-64 there's mention of some things to do for Ubuntu 16, but not 18.

**Comment by juliendelplanque** [comment]
Hello, can you create the page for that directly and propose a PR?

**Comment by juliendelplanque** [comment]
I'll do it. :-)

**Comment by juliendelplanque** [comment]
I created a basic page with your content [here](https://github.com/pharo-open-documentation/pharo-wiki/pull/182) can you please check it?
