### ISSUE TITLE
Guide on extensions: can extensions work if an attribute is modified?

### ISSUE THREAD

**Issue by 570gina** [pharo-open-documentation/pharo-wiki#145]
It seems from the guide that extensions are only for when methods are added. But will it be possible if an instance variable is also added? That is, extensions can also be done (in theory) to add instance variables. The guide doesn't state this specifically, but new pharo programmers might want to do it.

**Comment by jecisc** [comment]
Hi,

It is not possible to add instance variables as extensions. 

It is possible to do it via reflectivity but it is not recommended for production code.
