### ISSUE TITLE
Create a "Beginners" section in the README.md

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-open-documentation/pharo-wiki#163]
Because we start to have a lot of stuff in a "General" and some stuff there are for beginners.

**Comment by olekscode** [comment]
Yes, section **General** currently has the following pages:
* Setting up a new project
* Things beginners must learn
* Interesting things to know for beginners
* How to deal with baselines - Configure your project and its dependencies
* Pharo code export formats - Explanations about code formats used to export code to VCS such as git
* Extension methods - How to extend existing classes in your packages
* Traits - Structure to build classes via composition
* How to deploy a pharo application
* Some cool snippets in Pharo
* Progress bar - Display a progress bar to give feedback to the user
* Profiling - Measure the time and space your program takes to execute
* Menubar and World menu - A guide to configure and customize Pharo's menubar and world menu
* Pragmas - A guide on Pragmas, annotations to compiled methods to add additional properties
* Coding conventions

I think, it should be like this:
### Beginners
* Setting up a new project
* Things beginners must learn
* Interesting things to know for beginners

### General
* How to deal with baselines - Configure your project and its dependencies
* Pharo code export formats - Explanations about code formats used to export code to VCS such as git
* Extension methods - How to extend existing classes in your packages
* Traits - Structure to build classes via composition
* How to deploy a pharo application
* Some cool snippets in Pharo
* Progress bar - Display a progress bar to give feedback to the user
* Profiling - Measure the time and space your program takes to execute
* Menubar and World menu - A guide to configure and customize Pharo's menubar and world menu
* Pragmas - A guide on Pragmas, annotations to compiled methods to add additional properties
* Coding conventions

**Comment by juliendelplanque** [comment]
I agree.
