### ISSUE TITLE
Disable direct push and impose one review

### ISSUE THREAD

**Issue by jecisc** [pharo-open-documentation/pharo-wiki#179]
I suggest we enable branch protection on master.

The only way to commit on it would be via an approved PR.

Do you agree @juliendelplanque @olekscode ?

**Comment by juliendelplanque** [comment]
I agree, some people can not hold themselves 😄

**Comment by jecisc** [comment]
Done!

Now nobody can push to master and to merge a PR we need at least one review. Later if we add checks we can make sure they are green.
