### ISSUE TITLE
Add page on pragmas

### ISSUE THREAD

**Issue by jecisc** [pharo-open-documentation/pharo-wiki#19]

**Comment by juliendelplanque** [comment]
Wasn't this done with PR #78 ?

**Comment by jecisc** [comment]
No.

I want a real tutorial on pragma.

What they are. How to create a new one. How to collect them via the Pragma class. How to collect them via the PragmaCollector. Some examples.

**Comment by juliendelplanque** [comment]
Ok nice, I do not close this issue then 💯

**Comment by jecisc** [comment]
Done
