### ISSUE TITLE
Add a community page

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-open-documentation/pharo-wiki#221]
Where we could list:
- Twitter accounts related to Pharo
- Facebook profiles related to Pharo
- Blogs
- etc...

I talked to people at ESUG and some of them didn't know about Pharo club on facebook for example. I think it would be good to promote this kind of stuff around the community.

What do you think?

**Comment by juliendelplanque** [comment]
@jecisc bump

**Comment by jecisc** [comment]
It could indeed be cool, but I would add a big warning at the beginning that we are not responsible for the content and that we list things that seems relevant to us at the time we add it. (To avoid having pages that are currently Smalltalk blogs and that end up as political blogs)

**Comment by juliendelplanque** [comment]
Agree, the idea is to have a list of links alphabetically ranked that might interest people in the community.

We do not take the responsibility of the content published there...

**Comment by juliendelplanque** [comment]
This was done.
