### ISSUE TITLE
Guide on DataFrame

### ISSUE THREAD

**Issue by olekscode** [pharo-open-documentation/pharo-wiki#23]
Hello,
I would like to add a small guide about DataFrame.
Where should I put it?

I don't think it fits into `External projects > Data exchange`.
Perhaps `External projects > Data structures`?

**Comment by juliendelplanque** [comment]
In the end, I think it is too specific for Pharo wiki.
And now there is PharoAI community.
I guess I can close this issue.
Feel free to reopen it if you disagree.
