### ISSUE TITLE
Title level of glossary entries

### ISSUE THREAD

**Issue by sparagi** [pharo-open-documentation/pharo-wiki#250]
I humbly request that pull request [249](https://github.com/pharo-open-documentation/pharo-wiki/pull/249) be reverted, for two reasons:

- I'm documenting the architecture for my project, which will be deployed and used by many people who are unfamiliar with Pharo.  I'd like to link directly to specific terms, but now there are no anchors, so I can't.
- I sometimes use screen reader software, and it is much easier when the headings are marked up as headings.  Before, I could hear just the headings and then continue with the definition when I found the word I wanted.  Now I have to listen to at least some of the definitions I don't want in order to get to a specific  definition.  The usual recommendation is that [the headings decrease one level at a time](https://www.w3.org/WAI/tutorials/page-structure/headings/), but it sounds like there is no way to apply a stylesheet without switching to GitHub Pages.  I don't think this page would be confusing with a jump to header 4 or 5, as long as all the words were at the same heading level.

I am sorry to be late in commenting, and also maybe I should have reopened the existing issue instead of a new one?  I wish I had discovered issue [193](https://github.com/pharo-open-documentation/pharo-wiki/issues/193) earlier and commented there before y'all did work, but I just found the wiki recently and haven't had time to go through all the issues yet.

**Comment by sparagi** [comment]
The internal links from one glossary entry to another are also broken.

**Comment by juliendelplanque** [comment]
Hello,

First of all, thanks for contributing to this wiki!

I think the proposal is right, especially because of the broken links issue.

What do you think @jecisc ?

Julien

**Comment by jecisc** [comment]
Hi,

Thank you for contributing!

I agree with you. I think the best thing to do would be to use level 4 or 5 titles. For now, we'll merge your PR and reopen the previous issue.
