### ISSUE TITLE
Enh for baselines

### ISSUE THREAD

**Issue by Ducasse** [pharo-open-documentation/pharo-wiki#306]
It is not clear how to load a group in the baseline dependency

```
spec
				project: 'PetitParser'
					with: [ 
						spec 
   							baseline: 'PetitParser' 
   							with: [ spec repository: 'github://moosetechnology/PetitParser:v2.2.0/src'.
								spec loads: #('Tests') ]. ];
```

**Comment by jecisc** [comment]
This is explained in the section https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/Baselines.md#define-external-dependencies

**Comment by Ducasse** [comment]
Ok I could not find it. 
May be we promote as a subsection with Loading Group in the title.
