### ISSUE TITLE
Input methods in Pharo

### ISSUE THREAD

**Issue by SergeStinckwich** [pharo-open-documentation/pharo-wiki#320]
Write a document on inputs methods for Chinese, Japanese, Korean languages in Pharo

**Comment by DogLooksGood** [comment]
FYI, Input method works well in Windows. 

In macOS, pharo8 works, but pharo9 not.

In Linux, `-compositioninput` VM arguments works with Fcitx5.

**Comment by SergeStinckwich** [comment]
Thank you for your report, can you help us to write a short documentation in the pharo-wiki about methods inputs for Pharo ?

**Comment by DogLooksGood** [comment]
The only thing need be mentioned is that on Linux `-compositioninput` and `Fcitx5` is need.
should I make a PR for this?

**Comment by SergeStinckwich** [comment]
Yes I think so. A short document to say that input methods are working and how to use with Pharo.

**Comment by SergeStinckwich** [comment]
#321 has been merged.
