### ISSUE TITLE
Travis documentation page is outdated

### ISSUE THREAD

**Issue by jordanmontt** [pharo-open-documentation/pharo-wiki#327]
In the Pharo projects we moved to github actions. We should create also a wiki page of how to set up the smalltalk ci with github actions.

Also, in this travis page the code example is using:

```st
Pharo64-8.0
Pharo64-7.0
```

wiki page: https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/Travis.md

**Comment by jecisc** [comment]
I noted the Travis page as unmaintained since it became a pay to use service and I create a documentation on Github actions.

https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/GithubActions.md
