### ISSUE TITLE
Add link to pharo contribution guide

### ISSUE THREAD

**Issue by jecisc** [pharo-open-documentation/pharo-wiki#34]

**Comment by juliendelplanque** [comment]
Where is located this guide?

**Comment by jecisc** [comment]
https://github.com/pharo-project/pharo/wiki/Contribute-a-fix-to-Pharo

But maybe it could be migrated to here and updated.

**Comment by juliendelplanque** [comment]
Not sure because this guide should stay official.

**Comment by jecisc** [comment]
Done by Julien
