### ISSUE TITLE
Add page on profiling

### ISSUE THREAD

**Issue by dupriezt** [pharo-open-documentation/pharo-wiki#51]
*This page should go in Pharo Projects I guess*

# Profiling
Profiling a program is the act of measuring, for example, the time or space it takes to execute.

* [Time Profiling](#time-profiling)
  + [Method 1](#method-1)
  + [Method 2](#method-2)
  + [Method 3](#method-3)
* [Space Profiling](#space-profiling)

### Method 1
If `SimpleGridExample new open` is the program you want to profile, run:
```Smalltalk
TimeProfiler spyOn: [ SimpleGridExample new open ]
```
Result: a breakdown of the methods in which the program spent time.
![image](https://user-images.githubusercontent.com/32486709/50977046-afc35a00-14f1-11e9-9594-12b470d7e518.png)

### Method 2
If `SimpleGridExample new open` is the program you want to profile, **inspect**:
```Smalltalk
[ SimpleGridExample new open ] bench.
```
Result: the number of times the profiler was able to run the program per second.
![image](https://user-images.githubusercontent.com/32486709/50977140-e8fbca00-14f1-11e9-9503-f4c23a7f9c52.png)

### Method 3
You can access a UI for the time profiler tool via the menu.
![image](https://user-images.githubusercontent.com/32486709/50977854-6aa02780-14f3-11e9-8f9a-c9bfe60e847d.png)

Result: type your code in the top box and click "Profile it".
![image](https://user-images.githubusercontent.com/32486709/50977455-9d95eb80-14f2-11e9-98e3-225d0f9244fb.png)

## Space Profiling
Imagine you want to know how much instances of the classes Point and TextMorph there are in the system, and how much space they occupy. **Inspect**:
```Smalltalk
((SpaceTally new spaceTally: (Array with: TextMorph with: Point)) 
	asSortedCollection: [:a :b | a spaceForInstances > b spaceForInstances])
```
Result:
![image](https://user-images.githubusercontent.com/32486709/50977709-2b71d680-14f3-11e9-8ec0-5e5206501045.png)

**Comment by dupriezt** [comment]
@jecisc Here's a page on profiling programs

**Comment by dupriezt** [comment]
Pull-request #53

**Comment by jecisc** [comment]
Integrated
